#server:
#  host: ${HOST:192.168.99.100}
#  port: ${PORT:9000}
#
#spring:
#  application:
#    name: webapp
#  thymeleaf:
#    cache: false
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html